### ISSUE TITLE
Exploration: Rework of our internal model - specifically optical elements

### ISSUE THREAD

**Issue by Atraxus** [hz-b/rayx#227]
- We need a first iteration of an API for design parts of the optical elements and light sources
- Rayx-design as library for applications that need design parameters

**Comment by memoryleak47** [comment]
As explained in #188, this is a blocker for the new RML format.
Before implementing a new parser, we need to have a DesignElement format - in other words something like "Element" but with all the design parameters still in there.

We'd need a DesignElement later, eg. for the GUI - the user doesn't want to interact with our Shader-internal model, but probably prefers to access it through design parameters.

As we don't require DesignElement to be accessible within the shader, we can use unrestricted c++ to implement it.
In the design-element-variadic branch, I implemented a very templatey version for the DesignElement approach - featuring an automatic parser generator for toml.
We decided against merging it, due to it's complexity - which ultimately did not seem worth it.
